-- MySQL Script generated by MySQL Workbench
-- 07/17/15 16:01:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------
-- База даних для ЛКП "Лев"

-- -----------------------------------------------------
-- Schema animals
--
-- База даних для ЛКП "Лев"
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animals` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `animals` ;

-- -----------------------------------------------------
-- Table `animals`.`userOperationTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`userOperationTypes` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код типу операції користувача',
  `type` VARCHAR(10) NOT NULL COMMENT 'Назва операції',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`userTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`userTypes` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код типу користувача',
  `type` VARCHAR(10) NOT NULL COMMENT 'Вид користувача',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`userRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`userRoles` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код ролі користувача',
  `userRole` VARCHAR(10) NOT NULL COMMENT 'Назва ролі користувача',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код користувача',
  `name` VARCHAR(15) NOT NULL COMMENT 'Імя',
  `surname` VARCHAR(15) NOT NULL COMMENT 'Прізвище',
  `dateOfRegistration` DATE NOT NULL COMMENT 'Дата реєстрації',
  `userKindId` INT NOT NULL COMMENT 'Код виду користувача',
  `userRoleId` INT NULL COMMENT 'Код ролі користувача',
  `phone` VARCHAR(15) NULL COMMENT 'Телефон користувача',
  `address` VARCHAR(60) NULL COMMENT 'Поштова адреса користувача',
  `email` VARCHAR(30) NOT NULL COMMENT 'Адреса е-мейл',
  `socialLogin` VARCHAR(30) NULL COMMENT 'Логін в Фейсбуці чи інших соц-мережах',
  `password` VARCHAR(30) NOT NULL COMMENT 'Пароль',
  `roleId` INT NULL COMMENT 'Код ролі користувача',
  `organizationName` VARCHAR(50) NULL COMMENT 'Назва організації',
  `organizarionInfo` VARCHAR(70) NULL COMMENT 'Інформація про організацію',
  `isActive` TINYINT(1) NULL COMMENT 'Індикація блокування користувача',
  PRIMARY KEY (`ID`),
  INDEX `fkUserRoles_idx` (`userRoleId` ASC),
  INDEX `fkUserKinds_idx` (`userKindId` ASC),
  CONSTRAINT `fkUserRoles`
    FOREIGN KEY (`userRoleId`)
    REFERENCES `animals`.`userRoles` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkUserKinds`
    FOREIGN KEY (`userKindId`)
    REFERENCES `animals`.`userTypes` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`userOperationsLogger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`userOperationsLogger` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код операції',
  `date` DATETIME NOT NULL COMMENT 'Дата операції',
  `userID` INT NOT NULL COMMENT 'Код користувача, що виконав операцію',
  `operationID` INT NOT NULL COMMENT 'Код типу операції',
  `animalID` INT NOT NULL COMMENT 'Код тварини',
  PRIMARY KEY (`ID`),
  INDEX `fkUsers_idx` (`userID` ASC),
  INDEX `fkOperationKinds_idx` (`operationID` ASC),
  CONSTRAINT `fkOperationKinds`
    FOREIGN KEY (`operationID`)
    REFERENCES `animals`.`userOperationTypes` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkUsers`
    FOREIGN KEY (`userID`)
    REFERENCES `animals`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`animalTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`animalTypes` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код виду тварини',
  `type` VARCHAR(15) NOT NULL COMMENT 'Вид тварини',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `kind_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`citesTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`citesTypes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Код виду класифікації CITES',
  `type` VARCHAR(16) NOT NULL COMMENT 'Назва класифікації CITES',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`animalSizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`animalSizes` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код розміру',
  `size` VARCHAR(30) NOT NULL COMMENT 'Опис розміру',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `size_UNIQUE` (`size` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`animalSexTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`animalSexTypes` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код статі',
  `sex` VARCHAR(15) NOT NULL COMMENT 'Стать тварини',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`animalServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`animalServices` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код',
  `service` VARCHAR(15) NOT NULL COMMENT 'Вид сервісу',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `service_UNIQUE` (`service` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`animals` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Код',
  `sexTypeID` INT NULL COMMENT 'Стать',
  `typeID` INT NOT NULL COMMENT 'Код виду',
  `sizeID` INT NOT NULL COMMENT 'Код розміру',
  `citesID` INT NOT NULL COMMENT 'Код по довіднику CITES',
  `sort` VARCHAR(30) NULL COMMENT 'Порода',
  `transpNumber` VARCHAR(15) NULL COMMENT 'Номер мікрочіпа',
  `tokenNumber` VARCHAR(12) NULL COMMENT 'Номер бірки',
  `dateOfRegister` DATE NOT NULL COMMENT 'Дата реєстрації',
  `dateOfBirth` DATE NULL COMMENT 'Дата народження',
  `dateOfSterilization` DATE NULL COMMENT 'Дата стерилізації',
  `color` VARCHAR(20) NOT NULL COMMENT 'Окрас',
  `ownerID` INT NULL COMMENT 'Код власника',
  `address` VARCHAR(45) NULL COMMENT 'Адреса перебування',
  `status` TINYINT(1) NULL COMMENT 'Статус (жива/ні)',
  `image` VARCHAR(50) NULL COMMENT 'Шлях до фотографії',
  `serviceID` INT NOT NULL COMMENT 'Код сервісу',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `transpNumber_UNIQUE` (`transpNumber` ASC),
  INDEX `fkSex_idx` (`sexTypeID` ASC),
  INDEX `fkSize_idx` (`sizeID` ASC),
  INDEX `fkCites_idx` (`citesID` ASC),
  INDEX `fkKind_idx` (`typeID` ASC),
  INDEX `fkServices_idx` (`serviceID` ASC),
  INDEX `fkUser_idx` (`ownerID` ASC),
  CONSTRAINT `fkSex`
    FOREIGN KEY (`sexTypeID`)
    REFERENCES `animals`.`animalSexTypes` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkSize`
    FOREIGN KEY (`sizeID`)
    REFERENCES `animals`.`animalSizes` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkCites`
    FOREIGN KEY (`citesID`)
    REFERENCES `animals`.`citesTypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkType`
    FOREIGN KEY (`typeID`)
    REFERENCES `animals`.`animalTypes` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkServices`
    FOREIGN KEY (`serviceID`)
    REFERENCES `animals`.`animalServices` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkUser`
    FOREIGN KEY (`ownerID`)
    REFERENCES `animals`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
